### ISSUE TITLE
PlantUML: "The plugin you are using seems to generated a bad URL." on official PlantUML server

### ISSUE THREAD

**Issue by rmetzler** [hsanson/asciidoctor-plantuml#11]
The official plantuml.com server changed to URL format. Gitlab (and probably some other webapps) use asciidoctor-plantuml to create an image URL. Since the URL was changed, plantuml images are broken on Gitlab.

**broken example from your testsuite**

I copied the URL from your testsuite and changed the host https://github.com/hsanson/asciidoctor-plantuml/blob/b082ebd19942564a313debd72b9f174104c91527/test/test_plantuml.rb#L119
you can see this is broken

https://www.plantuml.com/plantuml/png/U9npA2v9B2efpStX2YrEBLBGjLFG20Q9Q4Bv804WIw4a8rKXiQ0W9pCviIGpFqzJmKh19p4fDOVB8JKl1QWT05kd5wq0

![broken](https://www.plantuml.com/plantuml/png/U9npA2v9B2efpStX2YrEBLBGjLFG20Q9Q4Bv804WIw4a8rKXiQ0W9pCviIGpFqzJmKh19p4fDOVB8JKl1QWT05kd5wq0)

**This works**

Just by adding `~1` it's fixed

https://www.plantuml.com/plantuml/png/~1U9npA2v9B2efpStX2YrEBLBGjLFG20Q9Q4Bv804WIw4a8rKXiQ0W9pCviIGpFqzJmKh19p4fDOVB8JKl1QWT05kd5wq0

![good](https://www.plantuml.com/plantuml/png/~1U9npA2v9B2efpStX2YrEBLBGjLFG20Q9Q4Bv804WIw4a8rKXiQ0W9pCviIGpFqzJmKh19p4fDOVB8JKl1QWT05kd5wq0)

**Links**

- Issue in Gitlab's issue tracker: https://gitlab.com/gitlab-org/gitlab/-/issues/216587
- Issue in PlantUMLs Forum: https://forum.plantuml.net/11432/the-plugin-you-are-using-seems-generate-private-gitlab-server?show=11433#a11433

**Comment by rmetzler** [comment]
Here is a comment where PlantUML devs say they added some magic bytes to signal the encoding: https://github.com/plantuml/plantuml/issues/117#issuecomment-623545016

**Comment by hsanson** [comment]
@rmetzler thanks for the the help.  I have merged and released a new version of the gem with these changes.
