### ISSUE TITLE
It should be possible to declare a PlantUML diagram in a literal block

### ISSUE THREAD

**Issue by Mogztter** [hsanson/asciidoctor-plantuml#13]
Currently, the extension only works on listing blocks. Since Asciidoctor Diagram recognizes both literal and listing blocks I think it would be great to also enable this extension on literal blocks.
I also believe that a literal block is semantically more accurate than a listing block (but it might be subjective). 

I think the main benefit would be that users won't have to update their document if they want to use Asciidoctor Diagram or this extension.

What do you think?

**Comment by hsanson** [comment]
@Mogztter sound reasonable. I did a simple change to include literal blocks.  Would appreciate if you can test this on your side.
