### ISSUE TITLE
Add support for block syntax

### ISSUE THREAD

**Issue by dalai4git** [hsanson/asciidoctor-plantuml#18]
Could you please also add support for the block macro syntax? 
See: https://github.com/asciidoctor/asciidoctor-diagram/#diagram-block-macro

I am often using `plantuml::file.puml[]` as it is shorter than the literal block version.

Thank you

**Comment by hsanson** [comment]
Thanks for raising the issue. Will need to study how to implement this but due to time limitations I don't think I can work on this any time soon.
