### ISSUE TITLE
Specifying plantuml.jar

### ISSUE THREAD

**Issue by vomus** [hsanson/asciidoctor-plantuml#30]
Hi!
I was wondering about a way of specifying a concrete plantuml.jar file for asciidoctor-pdf. The one coming with asciidoctor-pdf seems an older file than the version found in plantuml.com. Not being much of a ruby programmer I was looking through .rb for asciidoctor-pdf, and could not find any obvious parts...

Thanks!

**Comment by hsanson** [comment]
This gem does not use jar files directly. Instead requires a plantuml server running.
