### ISSUE TITLE
Breaking changes on plantuml_content() method.

### ISSUE THREAD

**Issue by hsanson** [hsanson/asciidoctor-plantuml#45]
Changes to the plantuml_content() method in this https://github.com/hsanson/asciidoctor-plantuml/pull/25 caused incompatibility with some softwares using this gem (:bow: ).

**Comment by hsanson** [comment]
@digitalmoksha sorry for late response (https://github.com/hsanson/asciidoctor-plantuml/pull/25#issuecomment-2465603760).  The new parent object needed for calling plantuml_content() method corressponds to as [Asciidoctor::AbstractNode](https://www.rubydoc.info/gems/asciidoctor/Asciidoctor/AbstractNode) object that asciidoctor gives automatically to the extension.

Since Gitlab uses this method directly on the HTML (nokogiri nodes) and cannot retrieve an AbstractNode is difficult to use the newer version of the gem as it is now.

I have made some changes in this PR: https://github.com/hsanson/asciidoctor-plantuml/pull/46 that would allow you to call the method with the first argment being null. In this case it will behave as it did before.  Appreciated if you can test it before I make a new release with this change.

**Comment by digitalmoksha** [comment]
I was able to get this solved by going straight to the `gen_url` method. So we can close this. Thanks for your help @hsanson!
